Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: python3.12
    MemorySize: 2048
    Environment:
      Variables:
        TABLE_NAME: !Ref Posts

Resources:
  ApiHandler:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 10
      Handler: posts.lambda_handler.lambda_handler
      Architectures: [arm64]
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Posts
      Events:
        RestApiEvent:
          Type: Api
          Properties:
            Path: '/{proxy+}'
            Method: ANY


  Posts:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH