Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: provided.al2023
    MemorySize: 2048
    Environment:
      Variables:
        TABLE_NAME: !Ref Posts

Resources:
  ApiHandler:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 13
      Handler: unused
      CodeUri: build/function.zip
      Architectures: [x86_64]
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Posts
      Events:
        HttpApiEvent:
          Type: HttpApi

  Posts:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH