Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: java21
    MemorySize: 2048
    Environment:
      Variables:
        TABLE_NAME: !Ref Posts

Resources:
  ApiHandler:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 10
      Handler: io.micronaut.function.aws.proxy.payload2.APIGatewayV2HTTPEventFunction
      Architectures: [x86_64]
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Posts
      Events:
        HttpApiEvent:
          Type: HttpApi
      SnapStart:
        ApplyOn: PublishedVersions
      AutoPublishAlias: SnapStart

  Posts:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH