Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: provided.al2
    MemorySize: 2048
    Environment:
      Variables:
        TABLE_NAME: !Ref Posts

Resources:
  ApiHandler:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 10
      Handler: unused
      CodeUri: build/libs/have_your_serverless_functions-unspecified-lambda.zip
      Architectures: [x86_64]
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Posts
      Events:
        HttpApiEvent:
          Type: HttpApi
        RestApiEvent:
          Type: Api
          Properties:
            Method: ANY
            Path: '/{proxy+}'

  Posts:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH